<?php
define('DB_SERVER',$_SERVER["DB_SERVER"]);
define('DB_USER',$_SERVER["DB_USER"]);
define('DB_PASSWD',$_SERVER["DB_PASSWD"]);
define('DATABASE',$_SERVER["DBSAFEBOX"]);
define('EMAIL',$_SERVER["IMIEL"]);
define('EMAILPWD',$_SERVER["CONTRAIMIEL"]);
define('RUTARCHIVOS',$_SERVER["RUTA"]);
define('RUTAPRIVADA', $_SERVER["RUTAPRIV"]);
define('RUTABORRADO',$_SERVER["BORRADO"]);
define('URL',$_SERVER["URLBASE"]);